apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube-app
  template:
    metadata:
      labels:
        app: youtube-app
    spec:
      containers:
      - name: youtube-app
        image: YOUR_DOCKERHUB_USERNAME/youtube-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-service
spec:
  selector:
    app: youtube-app
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
